export const questions = [
    {
      type: 'confirm',
      name: 'samefolder',
      message: 'Do you want to create the project in the current folder?',
      default: false,
    },
    {
      type: 'input',
      name: 'projectname',
      message: 'Enter the project name',
      when: (answers) => !answers.samefolder,
      default: 'my-nextjs-app',
    },
    {
      type: 'confirm',
      name: 'approuter',
      message: 'Do you want to use app router?',
      default: true,
    },
    {
      type: 'confirm',
      name: 'useTailwindCss',
      message: 'Do you want to use Tailwind Css?',
      default: true,
    },
    {
      type: 'confirm',
      name: 'useTypescript',
      message: 'Do you want to use typescript?',
      default: true,
    },
    {
      type: 'confirm',
      name: 'useESLint',
      message: 'Do you want to set up ESLint?',
      default: true,
    },
    {
      type: 'confirm',
      name: 'useHusky',
      message: 'Do you want to install Husky?',
      default: false,
    },
    {
      type: 'confirm',
      name: 'useCommitLint',
      message: 'Do you want to install commitlint?',
      default: false,
    },
    {
      type: 'list',
      name: 'testing',
      message: 'Which tool do you want to use for end-to-end testing?',
      choices: ['cypress', 'puppeteer', 'playwright', 'none'],
      default: 'none',
    },
    {
      type: 'list',
      name: 'unitTestingTool',
      message: 'Which tool do you want to use for unit testing?',
      choices: ['jest', 'mocha', 'none'],
      default: 'none',
    },
    {
      type: 'confirm',
      name: 'useSentry',
      message: 'Do you want to install Sentry for error tracking?',
      default: false,
    },
    {
      type: 'confirm',
      name: 'useCodeCov',
      message: 'Do you want to install Codecov for test coverage?',
      default: false,
    },
    {
      type: 'list',
      name: 'useAuth',
      message: 'Which tool do you want to use for authentication?',
      choices: ['nextauth', 'firebase', 'clerk', 'none'],
      default: 'none',
    },
    {
      type: 'confirm',
      name: 'usePwa',
      message: 'Do you want to use PWA service?',
      default: true,
    },
    {
      type: 'confirm',
      name: 'useSitemap',
      message: 'Do you want to generate a sitemap?',
      default: false,
    },
    {
      type: 'list',
      name: 'databaseTool',
      message: 'Which database tool would you like to use?',
      choices: ['Prisma', 'Drizzle', 'None'],
      default: 'None',
    },
    {
      type: 'list',
      name: 'deploymentPlatform',
      message: 'Which deployment platform would you like to use?',
      choices: ['Vercel', 'Netlify', 'None'],
      default: 'Vercel',
    },
  ];
  